apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
spec:
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
      - name: grid
        image: pixelart-grid:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: grid
spec:
  selector:
    app: grid
  ports:
  - port: 9100



